version: "2"
plugins:
  eslint:
    enabled: true
exclude_patterns:
  - "__tests__"
  - "__mocks__"
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 400
  method-complexity:
    config:
      threshold: 15
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 400
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 8
  similar-code:
    config:
      threshold: 150
  identical-code:
    config:
      threshold: 250
      